# 在这里配置AI玩家信息，name为对外显示名称，model为使用的LLM模型，local为True代表本地ollama模型，False为OpenAI模型
[[player]]
name = "DeepSeek"
model = "deepseek-r1:14b"
local = true

[[player]]
name = "Llama3.1"
model = "llama3.1:8b"
local = true

[[player]]
name = "Phi4"
model = "phi4"
local = true

[[player]]
name = "Qwen"
model = "qwen2.5:14b"
local = true

[[player]]
name = "Gemma3"
model = "gemma3:12b"
local = true

[[player]]
name = "ChatGPT"
model = "gpt-3.5-turbo"
local = false

[[player]]
name = "Qwen3"
model = "qwen3:14b"
local = true